# Generated by Django 3.0.8 on 2020-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articles_name',
            field=models.CharField(max_length=150, verbose_name='Articles name'),
        ),
    ]
